# Generated by Django 4.0.3 on 2022-03-22 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=50)),
                ('flat_type', models.CharField(max_length=50)),
                ('flat_area', models.CharField(max_length=50)),
                ('flat_price', models.CharField(max_length=50)),
                ('flat_description', models.TextField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society')),
            ],
            options={
                'db_table': 'flats',
            },
        ),
    ]
